# Generated by Django 4.2 on 2024-03-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmtask',
            name='cmd',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='algorithmtask',
            name='workspace',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='algorithmtask',
            name='workspace_dir',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
