# Generated by Django 4.2 on 2024-03-22 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_algorithmtask_cmd_algorithmtask_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmtask',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='algorithmtask',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='algorithmtask',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间'),
        ),
        migrations.AlterField(
            model_name='algorithmtask',
            name='cmd',
            field=models.CharField(blank=True, max_length=5012, null=True),
        ),
        migrations.AlterField(
            model_name='algorithmtask',
            name='pid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='algorithmtask',
            name='status',
            field=models.CharField(choices=[('running', 'running'), ('success', 'success'), ('canceled', 'canceled'), ('created', 'created')], default='created', max_length=32),
        ),
        migrations.AlterField(
            model_name='algorithmtask',
            name='workspace',
            field=models.CharField(blank=True, max_length=5012, null=True),
        ),
        migrations.AlterField(
            model_name='algorithmtask',
            name='workspace_dir',
            field=models.CharField(blank=True, max_length=5012, null=True),
        ),
    ]
