# Generated by Django 4.2 on 2024-03-25 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_algorithmtask_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmSystemRuntimeControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concurrency_limit', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'run_time_control',
            },
        ),
        migrations.CreateModel(
            name='AlgorithmSystemRuntimeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concurrency_status', models.IntegerField(default=2)),
                ('mark', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmUserRuntimeStatus',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('concurrency_status', models.IntegerField(default=9)),
                ('last_time_run', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='algorithmtask',
            name='status',
            field=models.CharField(choices=[('running', 'running'), ('success', 'success'), ('canceled', 'canceled'), ('created', 'created'), ('pending', 'pending')], default='created', max_length=32),
        ),
        migrations.CreateModel(
            name='AlgorithmProcessQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'pending'), ('running', 'running')], max_length=20)),
                ('is_task_submit', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.algorithmtask')),
            ],
            options={
                'db_table': 'task_queue',
            },
        ),
    ]
