# Generated by Django 4.2 on 2024-03-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_algorithmprocessqueue_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmsystemruntimecontrol',
            name='mark',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
