# Generated by Django 4.2 on 2024-03-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_algorithmsystemruntimecontrol_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmsystemruntimecontrol',
            name='user_limit',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='algorithmsystemruntimestatus',
            name='concurrency_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='algorithmuserruntimestatus',
            name='concurrency_status',
            field=models.IntegerField(default=0),
        ),
    ]
