# Generated by Django 4.2 on 2024-03-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_algorithmsystemruntimecontrol_user_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='algorithmsystemruntimestatus',
            table='run_time_status_system',
        ),
        migrations.AlterModelTable(
            name='algorithmuserruntimestatus',
            table='run_time_status_user',
        ),
    ]
