# Generated by Django 4.2 on 2024-03-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_algorithmsystemruntimestatus_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmtask',
            name='creator',
        ),
        migrations.AddField(
            model_name='algorithmtask',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='algorithmprocessqueue',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('accomplish', 'accomplish')], default='pending', max_length=20),
        ),
    ]
