# Generated by Django 4.2 on 2024-03-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_remove_algorithmtask_creator_algorithmtask_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmprocessqueue',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('accomplish', 'accomplish'), ('cancel', 'cancel')], default='pending', max_length=20),
        ),
    ]
